name: contapersone
description: A simple shared counter app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.3+44

# Disable sound null safety in Flutter beta channel
environment:
    sdk: ">=2.12.0 <=3.13.4"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    # Remember to update the tag for the prebuilt podf in Podfile
    cloud_firestore: ^6.1.2
    cupertino_icons: ^1.0.6
    firebase_analytics: ^12.1.2
    firebase_auth: ^6.1.4
    firebase_core: ^4.4.0
    fluttertoast: ^9.0.0
    http: ^1.3.0
    intl: ^0.20.2
    mobile_scanner: ^7.1.4
    qr_flutter: ^4.1.0
    share_plus: ^12.0.1
    url_launcher: ^6.1.11
    window_location_href: ^2.0.0
    vibration: ^3.1.3
    syncfusion_flutter_charts: ^32.2.3
    file: ^7.0.1
    rxdart: ^0.28.0
    universal_html: ^2.2.4
    app_links: ^7.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.14.3

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon.png"
    adaptive_icon_background: "#FF6E95CB"

flutter:
    uses-material-design: true
    generate: true

    assets:
        - assets/
