name: contapersone
description: A simple shared counter app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+38

# Disable sound null safety in Flutter beta channel
environment:
    sdk: ">=2.12.0 <=3.13.4"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    # Remember to update the tag for the prebuilt podf in Podfile
    cloud_firestore: ^4.12.2
    cupertino_icons: ^1.0.6
    firebase_analytics: ^10.6.3
    firebase_auth: ^4.12.1
    firebase_core: ^2.21.0
    firebase_dynamic_links: ^5.4.3
    fluttertoast: ^8.2.2
    http: ^0.13.6
    intl: ^0.18.1
    qr_code_scanner: ^1.0.1
    qr_flutter: ^4.1.0
    share: ^2.0.4
    url_launcher: ^6.1.11
    window_location_href: ^1.0.1+2
    vibration: ^1.8.3
    syncfusion_flutter_charts: ^21.2.4
    file: ^6.1.4
    rxdart: ^0.27.7
    universal_html: ^2.2.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon.png"
    adaptive_icon_background: "#FF6E95CB"

flutter:
    uses-material-design: true
    generate: true

    assets:
        - assets/
